//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weblogbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int sl { get; set; }
        public string articleID { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string writer_email { get; set; }
        public int writer_sl { get; set; }
        public string title { get; set; }
        public string articleBody { get; set; }
    
        public virtual User User { get; set; }
    }
}
