//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weblogbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fmap
    {
        public int fid { get; set; }
        public int followedBy_sl { get; set; }
        public int followed_sl { get; set; }
        public string followedBy_email { get; set; }
        public string followed_email { get; set; }
    }
}
