//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weblogbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public int sl { get; set; }
        public string subID { get; set; }
        public string name { get; set; }
        public int validity_months { get; set; }
        public decimal price { get; set; }
        public string postby { get; set; }
    }
}
